name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Adding Known Hosts
        run: ssh-keyscan -H 31.222.229.78 >> ~/.ssh/known_hosts

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Deploy to VPS
        run: |
          ssh root@31.222.229.78 << 'EOF'
            set -e
            cd sporttg
            git pull origin main
            docker compose down
            docker compose up -d --build
            echo "Deployment completed successfully"
          EOF
